version: '3.3'

services:
  ################ Postgresql ################
  postgres:
    container_name: ${DB_HOST}
    restart: unless-stopped
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

  ################# Back dev ###################
  back_dev:
    container_name: back_dev
    restart: unless-stopped
    image: node:19-alpine
    depends_on:
      - postgres
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    working_dir: /usr/src/app/
    command: sh -c "npm install && npm run build && npm run dev"
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./server:/usr/src/app/

  # ################# Front dev ###################
  # front_dev:
  #   container_name: front_dev
  #   restart: unless-stopped
  #   image: node:19-alpine
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 5173:5173
  #   working_dir: /usr/src/app/
  #   command: sh -c "npm install && npm run build && npm run dev"
  #   env_file:
  #     - .env
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - ./client:/usr/src/app/

volumes:
  pgdata:
    driver: local